name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Formatting
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: featurecount
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/transcript_config.yaml --lint"

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting
      - formatting
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Test workflow (alt-output)
      uses: ezherman/snakemake-github-action@b6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/altoutput_config.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --latency-wait 30"
    - name: Test workflow (transcripts no fastp)
      uses: ezherman/snakemake-github-action@b6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/transcript_nofastp.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --latency-wait 30"
    - name: Test workflow (mutpos)
      uses: ezherman/snakemake-github-action@b6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/mutpos_config.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --latency-wait 30"
    - name: Test workflow (hisat2 no fastp)
      uses: ezherman/snakemake-github-action@b6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/hisat2_skip_fastp.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --latency-wait 30"
    - name: Test workflow (transcripts)
      uses: ezherman/snakemake-github-action@b6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/transcript_config.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --latency-wait 30"
    - name: Test workflow (bam2EZbakR)
      uses: ezherman/snakemake-github-action@b6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/bam2bakR_config.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --latency-wait 30"
    - name: Test workflow (hisat2)
      uses: ezherman/snakemake-github-action@b6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/hisat2_config.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --latency-wait 30"
    - name: Clean up
      uses: ezherman/snakemake-github-action@b6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/transcript_nofastp.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --delete-all-output --latency-wait 30"
    - name: Test workflow (no cB)
      uses: ezherman/snakemake-github-action@b6bd319468ad9a049d37058554ebcd52eca38c92
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/nocB_config.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --latency-wait 30"